config/routes.rb
RideologyApp::Application.routes.draw do
  resources :users, :only => [:create, :new, :index, :show]
  resource :session, :only => [:create, :new, :destroy]
  root :to => "StaticPages#index"
  namespace :api do
    resources :ride_offers, :default => {:format => :json}
    resources :ride_takes, :only => [:create, :destroy]
  end
end

app/models/ride_offer.rb
class RideOffer < ActiveRecord::Base
  attr_accessible :date, :user_id, :origin, :destination, :spots, :cost
  
  belongs_to :user
  
  has_many :ride_takes, dependent: :destroy
  
  has_many(
    :passengers,
    :through => :ride_takes,
    :source => :user
  )
end

app/models/ride_take.rb
class RideTake < ActiveRecord::Base
  attr_accessible :user_id, :ride_offer_id
  
  belongs_to :user
  belongs_to :ride_offer
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :fname, :lname, :username, :password, :email
  validates :fname, :lname, :username, :presence => true
  validates :username, :uniqueness => true
  validates :password, :length => {:minimum => 6}, :on => :create
  attr_reader :password
  validate :ensure_token
  
  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end
  
  has_many :ride_takes
  has_many :ride_offers
  
  has_many(
    :takes,
    :through => :ride_takes,
    :source => :ride_offer
  )
  
  def self.find_by_credentials(username, secret)
    @user = User.find_by_username(username)
    return @user unless @user
    if @user.is_password?(secret)
      return @user
    else
      return nil
    end
  end
  
  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end
  
  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end
  
  def reset_token
    self.token = User.generate_token
  end
  
  def reset_token!
    self.token = User.generate_token
    self.save!
  end
  
  private
  
  def ensure_token
    self.token ||= User.generate_token
  end
  
end

app/controllers/api/ride_offers_controller.rb
class Api::RideOffersController < ApplicationController
  def new
  end

  def create
    @ride_offer = RideOffer.new(params[:ride_offer])
    @ride_offer.user_id = current_user.id
    if @ride_offer.save
      render json: @ride_offer
    else
      p @ride_offer.errors.full_messages.join(', ')
      render json: @ride_offer.errors.full_messages
    end
  end

  def edit
  end

  def update
  end

  def index
    if params[:search_origin] || params[:search_destination] || params[:search_date]
      if params[:search_origin].blank?
       origin = "%"
      else
       origin = "%#{params[:search_origin]}%"
      end
      if params[:search_destination].blank?
       destination = "%"
      else
       destination = "%#{params[:search_destination]}%"
      end
      if params[:search_date].blank?
        @ride_offers = RideOffer.where("origin LIKE ? AND destination LIKE ?", origin, destination)
      else
       date = params[:search_date]
       @ride_offers = RideOffer.where("origin LIKE ? AND destination LIKE ? AND date = ?", origin, destination, date)
      end
      render :json => {
        ride_offers: @ride_offers
      } 
    else
      @ride_offers = RideOffer.page(params[:page]).per(10)
      render :json => {
        ride_offers: @ride_offers,
        page_number: params[:page],
        total_pages: @ride_offers.total_pages
      }
    end
  end

  def show
  end

  def destroy
  end
end

app/controllers/api/ride_takes_controller.rb
class Api::RideTakesController < ApplicationController
  def create
    @ride_take = RideTake.new(params[:ride_take])
    @ride_take.user_id = current_user.id
    if @ride_take.save
      render json: @ride_take
    else
      render json: @ride_take.errors, status: 422
    end
  end

  def destroy
    @ride_take = RideTake.find_by_user_id_and_ride_offer_id(current_user.id, params[:ride_offer_id])
    @ride_take.destroy
    head :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    current_user.reset_token!
    session[:token] = nil
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in!(@user)
      AuthMailer.signup_email(@user).deliver!
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    if !!current_user
      @user = current_user
    else
      @user = User.new({username: "Guest", fname: "Captain", lname: "Cuddles"})
    end
    render "index"
  end
  
  def show
    if !!current_user
      @user = current_user
    else
      @user = User.new({username: "Guest", fname: "Captain", lname: "Cuddles"})
    end
    render "index"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ride_offers_helper.rb
module RideOffersHelper
end

app/helpers/ride_takes_helper.rb
module RideTakesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_token(session[:token])
    @current_user
  end
  
  def log_in!(user)
    session[:token] = user.token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RideologyApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<% if flash[:errors] && !flash[:errors].empty? %>
	<div class="alert alert-danger">
		<p><%= flash[:errors].join(', ') %></p>
	</div>
<% end %>

<div class="bberrors"></div>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-con">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/#/">Rideology - A Zimride clone for carpooling</a>
  </div>
      
  <div class="collapse navbar-collapse" id="nav-con">
    <ul class="nav navbar-nav">
      <li id="user-link" class="n-link"><a href="/#/user">My Rides</a></li>
      <li id="index-link" class="n-link"><a href="/#/index">Ride Index</a></li>
      <li id="post-link" class="n-link"><a href="/#/post">Post a Ride</a></li>
      <li id="search-link" class="n-link"><a href="/#/search">Search</a></li>
      <li><img style="z-index: 1050; padding-top: 10px" id="draggable" class="pop" src="/assets/glyphicons_005_car.png"></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if !!current_user %>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="" data-toggle="modal" data-target="#about-modal">About</a></li>
              <li><a href="" data-toggle="modal" data-target="#help-modal">Help</a></li>
              <li class="divider"></li>
              <li>
                <form action="<%= session_url %>" method="post">
                  <input type="hidden" name="_method" value="delete">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="submit" class="btn btn-default navbar-btn" value="Sign Out">
                </form>
            </li>
          </ul>
        </li>
      <% else %>
        <li>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="user[username]" value="guest">
            <input type="hidden" name="user[password]" value="password">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" class="btn btn-default navbar-btn" value="Login as Guest">
          </form>
        </li>
        <li><a href="/session/new">Sign in</a></li>
        <li><a href="/users/new">Create Accout</a></li>
      <% end %>
    </ul>
  </div>
</nav>

<body style="padding-top: 150px">
<%= yield %>

<div class="modal fade" id="about-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">About</h4>
      </div>
      <div class="modal-body">
        <p>Here's the repo for <a href="https://github.com/benjaminkreen/rideology">this</a> site.</p>
        <p>Car icon is from <a href="http://glyphicons.com/">Glyphicons</a></p>
        <p>Dainty draggable cursor by <a href="http://blog.arlenabraham.com/">Arlen</a></p> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="help-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Help</h4>
      </div>
      <div class="modal-body">
        <p>Drag the car icon into a ride on the index page or the search page to sign up for a ride</p>
        <p>Go to My Rides to view your offered rides and rides taken, including their passengers and drivers.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



</body>
</html>

app/views/ride_offers/create.html.erb
<h1>RideOffers#create</h1>
<p>Find me in app/views/ride_offers/create.html.erb</p>

app/views/ride_offers/destroy.html.erb
<h1>RideOffers#destroy</h1>
<p>Find me in app/views/ride_offers/destroy.html.erb</p>

app/views/ride_offers/edit.html.erb
<h1>RideOffers#edit</h1>
<p>Find me in app/views/ride_offers/edit.html.erb</p>

app/views/ride_offers/index.html.erb
<h1>RideOffers#index</h1>
<p>Find me in app/views/ride_offers/index.html.erb</p>

app/views/ride_offers/new.html.erb
<h1>RideOffers#new</h1>
<p>Find me in app/views/ride_offers/new.html.erb</p>

app/views/ride_offers/show.html.erb
<h1>RideOffers#show</h1>
<p>Find me in app/views/ride_offers/show.html.erb</p>

app/views/ride_offers/update.html.erb
<h1>RideOffers#update</h1>
<p>Find me in app/views/ride_offers/update.html.erb</p>

app/views/ride_takes/create.html.erb
<h1>RideTakes#create</h1>
<p>Find me in app/views/ride_takes/create.html.erb</p>

app/views/ride_takes/destroy.html.erb
<h1>RideTakes#destroy</h1>
<p>Find me in app/views/ride_takes/destroy.html.erb</p>

app/views/static_pages/index.html.erb
<div class="bbhandle">Backbone stuff goes here</div>
<script>
  $(document).ready(function(){
    RideologyApp.initialize();
    $('#draggable').draggable({revert: true});
  });
</script>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="row jumbotron">
	
	<h1>Create a User</h1>
	<form action="<%= users_url %>" method="POST">
    <div class="row">
  		<div class="col-xs-2">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  			<input type="text" name="user[username]" placeholder="username">
  			<br>
  			<br>
  			<input type="password" name="user[password]" placeholder="password">
  		</div>
  		<div class="col-xs-2">
  			<input type="text" name="user[fname]" placeholder="First Name">
  			<br>
  			<br>
  			<input type="text" name="user[lname]" placeholder="Last Name">
  			<br>
        <br>
        <input type="text" name="user[email]" placeholder="Email">
  		</div>
    </div>
    <div class="row">
      <div class="col-xs-2">
        <input type="submit" class="btn btn-primary" value="Create User">
      </div>
    </div>
	</form>
</div>